#!/usr/bin/env bash

# Central inventory for supported workstation configuration. Keep this file as
# the source of truth for documented/operator-facing variables.

# shellcheck disable=SC2034
WORKSTATION_CONFIG_KEYS=(
	DESKTOP_PACKAGES
	DRIVE_DIR
	GITHUB_TOKEN
	INFISICAL_API_URL
	INFISICAL_CLIENT_ID
	INFISICAL_CLIENT_SECRET
	INFISICAL_ENV
	INFISICAL_PROJECT_ID
	INFISICAL_SECRET_PATH
	INFISICAL_TOKEN
	INSTALL_DESKTOP
	INSTALL_NOMACHINE
	NOMACHINE_DEB_URL
	NOMACHINE_INSTALL_TIMEOUT
	PUBLIC_IPADDR
	RCLONE_CONFIG
	RCLONE_CONFIG_B64
	RCLONE_DIR_CACHE_TIME
	RCLONE_POLL_INTERVAL
	RCLONE_REMOTE
	RCLONE_REMOTE_PATH
	RCLONE_VFS_CACHE_DIR
	RCLONE_VFS_CACHE_MAX_AGE
	RCLONE_VFS_CACHE_MAX_SIZE
	SYNCTHING_DEVICE_NAME
	SYNCTHING_FOLDER_ID
	SYNCTHING_FOLDER_LABEL
	SYNCTHING_GUI_ADDRESS
	SYNCTHING_HOME
	SYNCTHING_PEER_ADDRESS
	SYNCTHING_PEER_DEVICE_ID
	SYNCTHING_PEER_DEVICE_IDS
	SYNCTHING_PEER_NAME
	SYNCTHING_RESCAN_INTERVAL
	TS_AUTHKEY
	TS_ENABLE_SSH
	TS_EXTRA_ARGS
	TS_HOSTNAME
	VAST_TCP_PORT_22
	VAST_TCP_PORT_4000
	WORKSPACE_CHOWN_RECURSIVE
	WORKSPACE_DIR
	WORKSTATION_ALLOW_CACHED_ENV
	WORKSTATION_ENV_FILE
	WORKSTATION_PASSWORD
	WORKSTATION_REPO_BRANCH
	WORKSTATION_REPO_DIR
	WORKSTATION_REPO_URL
	WORKSTATION_ROLE
	WORKSTATION_STRICT_VALIDATION
	WORKSTATION_USER
)

# Variables safe to import from /etc/workstation.env. Bootstrap credentials are
# intentionally omitted so cached env files cannot silently carry fetch tokens.
# shellcheck disable=SC2034
WORKSTATION_ENV_FILE_KEYS=(
	DESKTOP_PACKAGES
	DRIVE_DIR
	GITHUB_TOKEN
	INFISICAL_API_URL
	INFISICAL_ENV
	INFISICAL_PROJECT_ID
	INFISICAL_SECRET_PATH
	INSTALL_DESKTOP
	INSTALL_NOMACHINE
	NOMACHINE_DEB_URL
	NOMACHINE_INSTALL_TIMEOUT
	PUBLIC_IPADDR
	RCLONE_CONFIG
	RCLONE_CONFIG_B64
	RCLONE_DIR_CACHE_TIME
	RCLONE_POLL_INTERVAL
	RCLONE_REMOTE
	RCLONE_REMOTE_PATH
	RCLONE_VFS_CACHE_DIR
	RCLONE_VFS_CACHE_MAX_AGE
	RCLONE_VFS_CACHE_MAX_SIZE
	SYNCTHING_DEVICE_NAME
	SYNCTHING_FOLDER_ID
	SYNCTHING_FOLDER_LABEL
	SYNCTHING_GUI_ADDRESS
	SYNCTHING_HOME
	SYNCTHING_PEER_ADDRESS
	SYNCTHING_PEER_DEVICE_ID
	SYNCTHING_PEER_DEVICE_IDS
	SYNCTHING_PEER_NAME
	SYNCTHING_RESCAN_INTERVAL
	TS_AUTHKEY
	TS_ENABLE_SSH
	TS_EXTRA_ARGS
	TS_HOSTNAME
	VAST_TCP_PORT_22
	VAST_TCP_PORT_4000
	WORKSPACE_CHOWN_RECURSIVE
	WORKSPACE_DIR
	WORKSTATION_PASSWORD
	WORKSTATION_ROLE
	WORKSTATION_USER
)

declare -gA WORKSTATION_CONFIG_DEFAULTS=(
	[DESKTOP_PACKAGES]='xfce4 xfce4-goodies dbus-x11 x11-xserver-utils'
	[DRIVE_DIR]='/drive'
	[INFISICAL_API_URL]='https://app.infisical.com'
	[INFISICAL_ENV]='prod'
	[INFISICAL_SECRET_PATH]='/'
	[INSTALL_DESKTOP]='1'
	[INSTALL_NOMACHINE]='1'
	[NOMACHINE_DEB_URL]='https://www.nomachine.com/free/linux/64/deb'
	[NOMACHINE_INSTALL_TIMEOUT]='1800'
	[RCLONE_CONFIG]='/etc/workstation-rclone/rclone.conf'
	[RCLONE_DIR_CACHE_TIME]='1h'
	[RCLONE_POLL_INTERVAL]='1m'
	[RCLONE_REMOTE]='gdrive'
	[RCLONE_REMOTE_PATH]=''
	[RCLONE_VFS_CACHE_DIR]='/var/cache/workstation-rclone'
	[RCLONE_VFS_CACHE_MAX_AGE]='24h'
	[RCLONE_VFS_CACHE_MAX_SIZE]='50G'
	[SYNCTHING_FOLDER_ID]='workspace'
	[SYNCTHING_FOLDER_LABEL]='workspace'
	[SYNCTHING_GUI_ADDRESS]='127.0.0.1:8384'
	[SYNCTHING_PEER_ADDRESS]='dynamic'
	[SYNCTHING_PEER_NAME]='base'
	[SYNCTHING_RESCAN_INTERVAL]='3600'
	[TS_ENABLE_SSH]='1'
	[WORKSPACE_CHOWN_RECURSIVE]='0'
	[WORKSPACE_DIR]='/workspace'
	[WORKSTATION_ALLOW_CACHED_ENV]='0'
	[WORKSTATION_ENV_FILE]='/etc/workstation.env'
	[WORKSTATION_REPO_BRANCH]='main'
	[WORKSTATION_REPO_DIR]='/opt/workstation-infra'
	[WORKSTATION_REPO_URL]='https://github.com/oguzkaganozt/infra.git'
	[WORKSTATION_ROLE]='workstation'
	[WORKSTATION_STRICT_VALIDATION]='0'
	[WORKSTATION_USER]='workstation'
)

workstation_config_key_in_list() {
	local wanted="$1"
	shift
	local key
	for key in "$@"; do
		[[ "$key" == "$wanted" ]] && return 0
	done
	return 1
}

workstation_config_key_known() {
	workstation_config_key_in_list "$1" "${WORKSTATION_CONFIG_KEYS[@]}"
}

workstation_env_key_allowed() {
	workstation_config_key_in_list "$1" "${WORKSTATION_ENV_FILE_KEYS[@]}"
}

workstation_config_default() {
	local key="$1"
	local fallback="${2:-}"
	if [[ -v "WORKSTATION_CONFIG_DEFAULTS[$key]" ]]; then
		printf '%s' "${WORKSTATION_CONFIG_DEFAULTS[$key]}"
	else
		printf '%s' "$fallback"
	fi
}
